### PR TITLE
Updated Signup card

### PR DESCRIPTION
**Pull request by Akruti25**

### CODE REVIEW

**Comment by rajatmw1999** [comment]
@Akruti25 please include a screenshot here so I can review the design.

**Comment by rajatmw1999** [comment]
If the pic is not attached here in the comments, you can also make a new folder "screenshots" and include it in the PR.

**Comment by Akruti25** [comment]
Hey, I'll add a ss here. 
Screenshot (83)

**Comment by rajatmw1999** [comment]
Here are a few more changes.
1. Reduce the width of the whole card component. The size of the buttons as well.
2. Reduce the height as well.
3. The google signup button will stay white and turn blue only on hover.
4. The border-radius of the card is too much. Try to reduce it a bit.

**Comment by rajatmw1999** [comment]
Also, the folder structure is a bit changed. You might consider taking the pull before the next commit. As you can see that everyone component has its own folder in the front-end folder.

**Comment by rajatmw1999** [comment]
There are some conflicts due to the changed folder structure. You will need to take a pull before committing again.

**Comment by Akruti25** [comment]
I'll pull the entire thing tomorrow in the morning. As of now I can't find any folder for the navbar.

**Comment by rajatmw1999** [comment]
Sure. Try to bring the navbar links a bit to the right of the bar. It is too close to the brand name.

**Pull request closed without merging**
